@extends('layouts.app')
@section('title','Trades · ECFHL')
@section('content')
<div class="shell"><div class="page-head"><div class="eyebrow">Transaction archive</div><h1>Trades</h1><p>Search recorded ECFHL trades by season, franchise or player.</p></div>
<div class="toolbar"><select id="tradeSeason" class="control"><option value="">All seasons</option>@foreach($seasons as $s)<option>{{ $s }}</option>@endforeach</select><input id="tradeSearch" class="control" style="flex:1;min-width:220px" placeholder="Search team, player or draft pick…"></div>
<div id="tradeList" class="season-list">@foreach($trades as $t) @php($hay=strtolower(($t['from']??'').' '.($t['to']??'').' '.implode(' ',$t['from_items']??[]).' '.implode(' ',$t['to_items']??[])))
<article class="card trade-item" data-season="{{ $t['season'] }}" data-search="{{ $hay }}"><div class="section-title"><div><strong>{{ $t['from'] ?? '?' }} ↔ {{ $t['to'] ?? '?' }}</strong><br><span class="subtle">{{ $t['date'] ?? '' }}</span></div><span class="pill">{{ $t['season'] }}{{ !empty($t['vetoed']) ? ' · Vetoed' : '' }}</span></div><div class="grid-2"><div><strong>{{ $t['from'] ?? '?' }} sent</strong><ul>@foreach($t['from_items']??[] as $i)<li>{{ $i }}</li>@endforeach</ul></div><div><strong>{{ $t['to'] ?? '?' }} sent</strong><ul>@foreach($t['to_items']??[] as $i)<li>{{ $i }}</li>@endforeach</ul></div></div></article>
@endforeach</div></div>
@endsection
@push('scripts')<script>const q=document.getElementById('tradeSearch'),s=document.getElementById('tradeSeason');function filterTrades(){const n=q.value.toLowerCase();document.querySelectorAll('.trade-item').forEach(e=>e.style.display=((!s.value||e.dataset.season===s.value)&&(!n||e.dataset.search.includes(n)))?'':'none')}q.addEventListener('input',filterTrades);s.addEventListener('change',filterTrades);</script>@endpush