const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const handlers=new Map();
const node=()=>({addEventListener(type,fn){handlers.set(this.name+':'+type,[...(handlers.get(this.name+':'+type)||[]),fn])},removeEventListener(){}});
const trigger=Object.assign(node(),{name:'trigger',setAttribute(key,value){this[key]=value}}),panel={hidden:true};
const tips=Object.assign(node(),{name:'tips',querySelector:s=>s.includes('trigger')?trigger:panel,contains:el=>el===trigger||el===panel});
const document=Object.assign(node(),{name:'document',activeElement:null,getElementById:id=>id==='player-tips'?tips:null,querySelector:()=>null});
vm.runInNewContext(fs.readFileSync('public/season-players.js','utf8'),{document,window:{addEventListener(){},removeEventListener(){}}});
const fire=(key,event={})=>handlers.get(key).forEach(fn=>fn(event));
assert.equal(panel.hidden,true,'No automatic popup');
fire('tips:pointerenter',{pointerType:'mouse'});assert.equal(panel.hidden,false);
fire('tips:pointerleave',{pointerType:'mouse'});assert.equal(panel.hidden,true);
fire('trigger:focus');assert.equal(panel.hidden,false);
fire('document:keydown',{key:'Escape'});assert.equal(panel.hidden,true);
fire('trigger:click');assert.equal(panel.hidden,false);assert.equal(trigger['aria-expanded'],'true');
fire('tips:pointerleave',{pointerType:'mouse'});assert.equal(panel.hidden,false,'Tapped tips remain open');
fire('document:click',{target:{closest:()=>null},button:0});assert.equal(panel.hidden,true);
fire('trigger:click');fire('trigger:click');assert.equal(panel.hidden,true,'Second tap closes');
fire('tips:pointerenter',{pointerType:'touch'});assert.equal(panel.hidden,true);
console.log('Player tips passed: hidden initially, hover, focus, touch toggle, outside dismissal and Escape.');
